version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: cinewise-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    networks:
      - cinewise-network

  mongo-express:
    image: mongo-express:latest
    container_name: cinewise-mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=adminpassword
      - ME_CONFIG_MONGODB_SERVER=mongodb
    depends_on:
      - mongodb
    networks:
      - cinewise-network

volumes:
  mongodb_data:
    name: cinewise-mongodb-data

networks:
  cinewise-network:
    name: cinewise-network
    driver: bridge